version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6380:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
